version: "3.8"
services:
  db:
    image: postgres:bullseye
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  #aspriapp:
  #  build: ./
  #  container_name: aspriapp1
  #  restart: always
  #  ports:
  #    - 3000:3000
  #depends_on:
  # - db
  # environment:
  #  - DATABASE_URL=postgresql://user:password@db:5432/db?schema=public
  #   volumes:
#      - ./frontend:/usr/src/app
